### ISSUE TITLE
Fix the distances between about us and get in touch on mobile version 

### ISSUE THREAD

**Issue by artemis-toumazi** [oorestisime/kayon-decor#43]
On mobile version, the distances between categories and about us, FAQ and get in touch in the menu bar are not the same.

**Comment by KostasTheodoro** [comment]
@artemis-toumazi we sure we want that?

**Comment by artemis-toumazi** [comment]
@KostasTheodoro Of course! Are we sure that we are talking about the same issue? :)

**Comment by artemis-toumazi** [comment]
I want the same distances between all the things that appear in the menu bar. I don't care the exact distance, just is the same. I prefer make them all like the categories.

**Comment by KostasTheodoro** [comment]
@artemis-toumazi maybe get a preview to see how it looks and you tell me what you prefer?
